import React from "react";

export default function Policy() {
    return (
        <div className="policy">
        <div>
           
         <p>1. Acknowledgment and Acceptance of Terms
"P. LEAGUE+" provides services (hereinafter referred to as "the Service") in accordance with these Terms of Service. When a member completes the registration process for the Service or starts using the Service, it indicates that they have read, understood, and agreed to all the contents of these Terms of Service and fully accept the current and future service items and contents of the Service. The Service reserves the right to modify or change the contents of these Terms of Service at any time, and the modified terms will be posted on the website. The Service will not individually notify members, and it is recommended that members pay attention to such modifications or changes at any time. Continuing to use the Service after any modification or change implies that the member has read, understood, and agreed to accept such modifications or changes. If you disagree with the revised or updated method of the Terms of Service, or do not accept any other provision of these Terms of Service, you should immediately stop using the Service.

If the member is a minor under the age of twenty, the member's parent (or guardian) must read, understand, and agree to all the contents of this agreement and its subsequent modifications before registering as a member, using, or continuing to use the Service. When a member uses or continues to use the Service, it is presumed that the member's parent (or guardian) has read, understood, and agreed to accept all the contents of this agreement and its subsequent modifications.

Members and the Service agree that all contents of using the Service, including expressions of intent, shall be in the form of electronic documents.

To ensure the protection of members' personal data, privacy, and consumer rights, members' personal data will be used during the transaction process.
</p>

<p>2. Member's Registration Obligations
Members must provide their correct and latest information according to the prompts on the Service's registration form and must not register in the name of a third party. Each member can only register one account and cannot register multiple accounts.

Members must maintain and promptly update their personal information to ensure its accuracy to receive the best service.

If a member provides any incorrect or false information, fails to provide information as instructed, lacks necessary information, has duplicated accounts, or any other situation deemed inappropriate by the Service, the Service has the right to suspend or terminate the member's account without prior notice and refuse the member's use of the Service.</p>

<p>3. Privacy Policy of the Service
The registration and other specific data of members are protected and regulated by the Service's Privacy Policy.</p>
<p>4. Member Account, Password, and Security
After completing the Service's registration process, members will receive a specific password and account number. It is the member's responsibility to maintain the confidentiality of the password and account.

Any actions taken with the password and account will be deemed to have been used by the member, and the member shall bear full responsibility for all actions conducted with their password and account.

Members agree to the following:

Immediately notify the Service if the member's password or account is stolen or if any other security issues occur.
End each session after using the account.
The member's account, password, and membership rights are for the individual use and enjoyment of the member only and may not be lent, transferred, or shared with others.

The Service will not be liable for any damage caused by the theft, misuse of the account and password, or any other circumstances where the Service cannot identify whether it was used by the member themselves unless it is proven to be due to a reason attributable to the Service.

If the Service is aware that a member's account password is indeed being used by someone else, the Service will immediately suspend the use of that account (including the processing of transactions generated by that account).</p>

<p>5. Protection of Children and Adolescents
To ensure the safety of children and adolescents using the internet and to avoid invasion of privacy, parents (or guardians) should fulfill the following obligations: Children under the age of twelve should be accompanied by a parent or guardian when using the Service, and adolescents over the age of twelve but under the age of eighteen should consider whether to give consent before using the Service.</p>
<p>6. Legal Obligations and Promises of Users
Members promise never to use the Service for any illegal purposes or by any illegal means and agree to abide by the relevant regulations of the Republic of China and all international practices of using the internet. If members are from outside the Republic of China, they agree to comply with the laws of their country or region. Members agree and guarantee not to use the Service to engage in acts that infringe on the rights of others or are illegal, including but not limited to:

Publishing or transmitting any slanderous, insulting, threatening, offensive, indecent, obscene, false, against public order or good morals, or any other illegal text, pictures, or any form of files.
Infringing or damaging the reputation, privacy, trade secrets, trademark rights, copyright, patents, other intellectual property rights, and other rights of the Service or others.
Violating confidentiality obligations under law or contract.
Impersonating others in using the Service.
Transmitting or spreading computer viruses.
Engaging in unauthorized commercial behavior without the prior authorization of the Service.
Posting, transmitting, sending spam, chain letters, illegal or unauthorized multilevel marketing messages, and advertisements, etc., or storing any data that infringes on the intellectual property rights of others or violates laws.
Engaging in behaviors that cause trouble, displeasure to other users or third parties of the Service, or violate general internet etiquette.
Other behaviors not in accordance with the intended use of the Service or deemed inappropriate by the Service.</p>

<p>7. Changes to Service Content and Sending of Newsletters and EDM
The Service has the right to increase, decrease, change, or terminate related service items or contents according to business needs and actual situations without individual notice to members.

Members agree that the Service may add, modify, or terminate related activities according to the actual execution situation and choose the most suitable way to inform members.

Members agree that the Service may periodically send newsletters or product information (EDM) to the email accounts registered by members. When members indicate refusal to accept marketing after receiving the message, the Service will stop sending marketing messages.</p>

<p>8. Suspension and Interruption of Service
The Service will maintain the normal operation of the system and services with reasonable technology and methods. However, the Service has the right to stop or interrupt the provision of the Service in the following situations:

When the electronic communication equipment of the Service website undergoes necessary maintenance and construction.
When a sudden failure of electronic communication equipment occurs.
When the electronic communication service applied for by the Service website is stopped and cannot provide services.
When forces beyond the control of the Service, such as natural disasters, or other factors not attributable to the Service, make it impossible for the Service website to provide services.</p>

<p>9.  Limitation and Exclusion of Liability
The Service provides all functions as is at the time of use, and the Service does not bear any express or implied warranty responsibility for its performance, speed, completeness, reliability, security, accuracy, etc.

The Service does not guarantee that emails or content sent from the Service's website, servers, domains, etc., will not contain harmful elements such as computer viruses; nor does it guarantee that the transmission and storage of emails, files, or data will be correct without errors, disconnections, etc. The Service is not liable for damages caused by the failure, loss, or error of the transmission or storage of such emails, files, or data.</p>
<p>10. Protection of Intellectual Property Rights
The software or programs used by the Service and all content on the website, including but not limited to works, pictures, files, information, data, website structure, website layout, webpage design, are owned by the Service or other right holders according to the law, including but not limited to trademark rights, patent rights, copyrights, trade secrets, and other intellectual property rights. No one may use, modify, reproduce, publicly broadcast, derivative works, distribute, publish, reverse engineer, decompile, or reverse compile without authorization. If members wish to quote or reproduce the aforementioned software, programs, or website content, they must obtain the prior written consent of the Service or other right holders according to the law. Respecting intellectual property rights is an obligation that members should fulfill. If violated, members shall compensate the Service and related right holders for damages (including but not limited to litigation costs and attorney fees).

Under the principle of respecting others' intellectual property rights, members agree not to engage in infringing activities on others' intellectual property rights while using the Service.

If members are involved in infringement, the Service may suspend all or part of the Service or directly cancel the member's account.

If you find that intellectual property rights have been infringed, please send the infringement situation and contact information, along with a truthful statement and declaration of legal intellectual property rights, to the Service by email at law@pleagueofficial.com (Please note! This mailbox is for limited purposes. Emails not related to infringement notifications sent to this address will not be processed. If Service members have any questions, please inquire at the customer service center.)</p>

</div>
</div>
    )
}